import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = fileURLToPath(new URL('../', import.meta.url))
const command = Bun.spawn(['cargo', 'build', '--manifest-path', `${root}wasm/Cargo.toml`,
  '--locked', '--release', '--target', 'wasm32-unknown-unknown'], {
  stdout: 'inherit', stderr: 'inherit', env: { ...process.env, CARGO_TARGET_DIR: `${root}wasm/target` },
})
if (await command.exited !== 0) process.exit(1)
const bytes = await readFile(`${root}wasm/target/wasm32-unknown-unknown/release/gum_png.wasm`)
if (WebAssembly.Module.imports(new WebAssembly.Module(bytes)).length) {
  throw new Error('The PNG WASM module must not depend on host imports')
}
// Embed the release artifact so browsers and bundlers need no asset loader,
// fetch, filesystem access, or asynchronous initialization. Compilation is lazy.
await mkdir(`${root}src/generated`, { recursive: true })
await writeFile(`${root}src/generated/wasm.ts`,
  '// Generated by bun run build. Do not edit. See wasm/Cargo.lock and THIRD_PARTY_NOTICES.md.\n'
  + `export const wasm_base64: string = '${bytes.toString('base64')}'\n`)
console.log(`tiny-skia WASM: ${bytes.length.toLocaleString()} bytes`)

// Ship the licenses for the exact locked dependencies alongside the binary.
const metadata = Bun.spawnSync(['cargo', 'metadata', '--manifest-path', `${root}wasm/Cargo.toml`,
  '--locked', '--offline', '--format-version', '1'], { stdout: 'pipe', stderr: 'pipe' })
if (metadata.exitCode) throw new Error(metadata.stderr.toString())
const packages: { name: string; version: string; license: string; manifest_path: string }[] =
  JSON.parse(metadata.stdout.toString()).packages
const notices = ['# Third-party notices\n\nThe bundled WebAssembly module is built from tiny-skia and the dependencies\n'
  + 'pinned in `wasm/Cargo.lock`. Their license texts follow.\n']
for (const pkg of packages.sort((a, b) => `${a.name} ${a.version}`.localeCompare(`${b.name} ${b.version}`))) {
  if (pkg.name === 'gum-png') continue
  notices.push(`\n## ${pkg.name} ${pkg.version}\n\nLicense: ${pkg.license}\n`)
  const directory = dirname(pkg.manifest_path)
  for (const file of (await readdir(directory)).sort()) {
    if (/^(LICENSE|NOTICE|COPYING)/.test(file)) {
      notices.push(`\n### ${file}\n\n\`\`\`text\n${(await readFile(join(directory, file), 'utf8')).trim()}\n\`\`\`\n`)
    }
  }
}
await writeFile(`${root}THIRD_PARTY_NOTICES.md`, notices.join(''))
